# Generated by Django 2.2.5 on 2019-11-13 21:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_id', models.BigIntegerField()),
                ('customer_id', models.IntegerField(default=0)),
                ('link_id', models.BigIntegerField(null=True)),
                ('image', models.CharField(default='no image', max_length=1000, null=True)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('reg_date', models.DateTimeField(default='2019-11-13 21:52:08', null=True)),
                ('update_date', models.DateTimeField(default='2019-11-13 21:52:08', null=True)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('link_url', models.CharField(max_length=255)),
                ('favicon_url', models.CharField(max_length=1000, null=True)),
                ('image_url', models.CharField(max_length=1000, null=True)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('reg_date', models.DateTimeField(default='2019-11-13 21:52:09', null=True)),
                ('update_date', models.DateTimeField(default='2019-11-13 21:52:09', null=True)),
            ],
            options={
                'db_table': 'link',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('coordinates', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('category', models.IntegerField(default=0)),
                ('image', models.CharField(default='no image', max_length=1000, null=True)),
                ('reg_date', models.DateTimeField(default='2019-11-13 21:52:08', null=True)),
                ('update_date', models.DateTimeField(default='2019-11-13 21:52:08', null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_id', models.BigIntegerField()),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'crawlingUrl',
            },
        ),
    ]
