# Generated by Django 2.2.5 on 2019-11-10 21:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_id', models.BigIntegerField()),
                ('image', models.CharField(default='no image', max_length=1000, null=True)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('reg_date', models.DateTimeField(null=True)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'crawling_article',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('coordinates', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('category', models.IntegerField(default=0)),
                ('image', models.CharField(default='no image', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location_id', models.BigIntegerField()),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'crawling_url',
            },
        ),
    ]
