# Generated by Django 2.2.5 on 2019-09-28 06:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('location_id', models.BigIntegerField()),
                ('link_id', models.BigIntegerField(null=True)),
                ('image', models.CharField(default='no image', max_length=255, null=True)),
                ('summary', models.CharField(max_length=255, null=True)),
                ('reg_date', models.DateTimeField(null=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('coordinates', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('category', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('used_time', models.FloatField(default=0)),
                ('image', models.CharField(default='no image', max_length=255, null=True)),
            ],
        ),
    ]
